# Generated by Django 5.2.5 on 2025-08-31 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='victimreport',
            options={'ordering': ['-reported_at']},
        ),
        migrations.AddField(
            model_name='victimreport',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='victimreport',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('triaged', 'Triaged'), ('rescued', 'Rescued')], default='new', max_length=10),
        ),
        migrations.AlterModelTable(
            name='victimreport',
            table=None,
        ),
    ]
