# Generated by Django 5.2.5 on 2025-08-30 15:06

import django.contrib.gis.db.models.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VictimReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('needs', models.JSONField(default=dict)),
                ('priority', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('new', 'New'), ('triaged', 'Triaged'), ('rescued', 'Rescued')], default='new', max_length=20)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'victim_reports',
            },
        ),
    ]
