# Generated by Django 5.2.5 on 2025-08-30 15:06

import django.contrib.gis.db.models.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoadSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField()),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('flooded', 'Flooded'), ('blocked', 'Blocked')], default='normal', max_length=20)),
                ('last_checked', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'road_segments',
            },
        ),
    ]
