# Generated by Django 5.2.5 on 2025-08-30 15:06

import django.contrib.gis.db.models.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloodEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('confidence', models.FloatField()),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'flood_events',
            },
        ),
    ]
