# Generated by Django 5.2.5 on 2025-09-04 03:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitter', 'Twitter/X'), ('youtube', 'YouTube'), ('instagram', 'Instagram'), ('facebook', 'Facebook')], max_length=20)),
                ('post_id', models.CharField(max_length=255, unique=True)),
                ('content', models.TextField()),
                ('author_username', models.CharField(max_length=255)),
                ('author_display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('post_url', models.URLField()),
                ('created_at', models.DateTimeField()),
                ('engagement_metrics', models.JSONField(default=dict)),
                ('location_data', models.JSONField(blank=True, default=dict, null=True)),
                ('media_urls', models.JSONField(blank=True, default=list)),
                ('processed', models.BooleanField(default=False)),
                ('flood_relevant', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at_db', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'social_media_posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='floodevent',
            options={'ordering': ['-detected_at']},
        ),
        migrations.AddField(
            model_name='floodevent',
            name='author_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='floodevent',
            name='engagement_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='floodevent',
            name='location_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodevent',
            name='original_post_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='floodevent',
            name='post_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodevent',
            name='post_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodevent',
            name='severity_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='floodevent',
            name='social_media_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='floodevent',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='floodevent',
            name='source',
            field=models.CharField(choices=[('sar_ml', 'SAR ML Detection'), ('social_media', 'Social Media'), ('weather_api', 'Weather API'), ('gdacs', 'GDACS'), ('manual', 'Manual Report')], default='manual', max_length=50),
        ),
    ]
