# Generated by Django 5.2.5 on 2025-09-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_app', '0002_socialmediapost_alter_floodevent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floodevent',
            name='severity_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='platform',
            field=models.CharField(choices=[('reddit', 'Reddit'), ('youtube', 'YouTube'), ('news', 'News API'), ('telegram', 'Telegram'), ('twitter', 'Twitter/X'), ('instagram', 'Instagram'), ('facebook', 'Facebook')], max_length=20),
        ),
    ]
