# Generated by Django 5.2.5 on 2025-09-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_app', '0003_alter_floodevent_severity_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediapost',
            name='gdacs_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='platform',
            field=models.CharField(choices=[('gdacs', 'GDACS Official'), ('news', 'India News'), ('reddit', 'India Reddit'), ('youtube', 'YouTube'), ('weather', 'India Weather'), ('telegram', 'Telegram'), ('twitter', 'Twitter/X'), ('instagram', 'Instagram'), ('facebook', 'Facebook')], max_length=20),
        ),
    ]
