# Generated by Django 5.2.5 on 2025-09-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_app', '0004_socialmediapost_gdacs_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediapost',
            name='author_display_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='author_username',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='post_id',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='post_url',
            field=models.URLField(max_length=1000),
        ),
    ]
