# Generated by Django 5.2.5 on 2025-09-13 09:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_app', '0005_alter_socialmediapost_author_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floodevent',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='floodevent',
            name='detected_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='floodevent',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='floodevent',
            name='source',
            field=models.CharField(choices=[('social_media', 'Social Media'), ('weather_api', 'Weather API'), ('sar_ml', 'SAR ML Model'), ('gdacs', 'GDACS'), ('manual', 'Manual Report')], default='manual', max_length=50),
        ),
    ]
