# Generated by Django 5.2.5 on 2025-09-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_app', '0006_alter_floodevent_confidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floodevent',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
