# Generated by Django 5.2.5 on 2025-09-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_app', '0007_alter_floodevent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floodevent',
            name='author_username',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='floodevent',
            name='original_post_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='floodevent',
            name='post_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
